### ISSUE TITLE
The command bar is purple

### ISSUE THREAD

**Issue by AffanIndo** [arcticicestudio/nord-tmux#15]
The tab bar has nord colorscheme, but the command bar has this purple color
![powerask](https://user-images.githubusercontent.com/18306510/32361140-981abcb6-c08f-11e7-955b-dcd16ad61959.png)
This happened in rxvt-unicode, xfce terminal and xterm.

**Comment by AffanIndo** [comment]
![screenshot from 2017-11-03 20-17-26](https://user-images.githubusercontent.com/18306510/32375478-4ae759aa-c0d4-11e7-8f1e-d1603726fbe5.png)
My split pane color became purple too even though on the .tmux.conf it is set to cyan. This only happened when I activate nord-tmux plugin

**Comment by arcticicestudio** [comment]
Does your terminal support 24-bit *True color* and which `tmux` version are you running?
`tmux` supports 24-bit *True color* since version [2.2][vercom].

urxvt for example is know to [parsing ANSI color sequences, but approximating them to 256 palette][gist-urxvt].

Please start `tmux` and run

```sh
tmux info | grep Tc
```

If the output is `Tc: (flag) true` your `tmux` supports true color, otherwise the output `Tc: [missing]` indicates that `tmux` has no *True color* support.

You can run this inside `tmux` to test the 24-bit colors:

```awk
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

If the line looks "stepwise" `tmux` does not use 24-bit *True color*:

![gh-15-scrot-no-24bit-true-color](https://user-images.githubusercontent.com/7836623/32377997-cce9d4bc-c0a9-11e7-81fa-3ced06cc2b28.png)

Otherwise the line should have smooth transitions:

![gh-15-scrot-24bit-true-color](https://user-images.githubusercontent.com/7836623/32378003-cfb7be70-c0a9-11e7-94b5-5154d72e19b2.png)

The `$TERM` environment variable is important for `tmux` as also clarified in the official [tmux FAQ][faq]. The variable must be initialized with a terminal that supports 256 colors (`*-256color`). More information about 24-bit color terminal support can be found in the awesome [Arch Linux Wiki][wiki]. 

If your terminal supports *True color* you should make sure to remove the `default-terminal` configuration from your `~/.tmux.conf` and add the `terminal-overrides` option instead:

```diff
-set -g default-terminal "xterm-256color"
+set-option -ga terminal-overrides ",xterm-256color:Tc"
```

**This will reflect your actual `$TERM` outside of `tmux`!**

Replace the `xterm-256color` with your desired terminal e.g. `rxvt-unicode-256color`. Also make sure to keep the important `Tc` [terminfo][ti] extension flag!

[gist-urxvt]: https://gist.github.com/XVilka/8346728#parsing-ansi-colour-sequences-but-approximating-them-to-256-palette
[faq]: https://github.com/tmux/tmux/wiki/FAQ#what-is-term-and-what-does-it-do
[vercom]: https://github.com/tmux/tmux/commit/427b8204268af5548d09b830e101c59daa095df9
[wiki]: https://wiki.archlinux.org/index.php/Tmux#24-bit_color
[ti]: https://en.wikipedia.org/wiki/Terminfo

**Comment by AffanIndo** [comment]
![screenshot from 2017-11-04 16-01-24](https://user-images.githubusercontent.com/18306510/32404005-04d46330-c17a-11e7-92ae-9c49b268e949.png)
Yeah, you're right. Previously I have Tmux 2.1 and no Tc.
But now I compiled 2.6 and it works.
But the Awk thingy become weird (and it blinking) even though my problem has fixed (split bar became blue but not my cyan tho). Is this normal?

**Comment by arcticicestudio** [comment]
Nice to see that it fixed your problem :smile: 

The weird output might be related to some implementation details regarding the escape codes (`033`, `\e`) or some `awk` version incompatibilities, but as long as this problem is only limited to the test code you can ignore it.

Have you tried to logout from the current session and check again after login? The `$TERM` env is loaded on login so the change can not be tested on-the-fly.

**Comment by AffanIndo** [comment]
Yea, still weird. But my problem's fixed anyway :) thanks. Just the True color thingy

**Comment by arcticicestudio** [comment]
Maybe there's another compatibility problem with `urxvt`. You can check out the awesome Gist about [Colours in terminal][g] that covers almost all topics and includes a lot of troubleshooting documentation.

[g]: https://gist.github.com/XVilka/8346728

**Comment by pannnnn** [comment]
The command bar is yellow. And I have smooth transitions printed out by the command line you provided. And 'tmux info | grep Tc' is set correctly. The only thing that I think that could possibly cause this problem is that I am using Alacritty which is not in the installation list before installing Nord tmux. Could you please help me with this? That would be really appreciated

**Comment by arcticicestudio** [comment]
@pannnnn Can you please try to reproduce the problem with a clean Vim config that only contains the activation for the `colorscheme` but nothing else like plugins, settings or global variables?

**Comment by arcticicestudio** [comment]
@pannnnn Any updates on this? Have you been able to reproduce the problem with a clean config?
Also I must have overlooked that you wrote you're using Alacritty, but couldn't find a matching terminal color scheme in the list. There is [Nord Alacritty](https://github.com/arcticicestudio/nord-alacritty) and it is required to be installed when you're using Alacritty, otherwise the root cause of your problem is that the Nord colors are simply not available and instead the color your currently active theme is used which might use a different color ordering.
