### ISSUE TITLE
Weird Symbols instead of arrow Glyphs

### ISSUE THREAD

**Issue by Kaddu720** [arcticicestudio/nord-tmux#39]
I've tried to install this theme on my ubuntu pc and instead of the arrow glyphs that you're supposed to get, I get these weird symbols.

![Screenshot from 2019-09-30 22-04-44](https://user-images.githubusercontent.com/51177491/65935573-604df280-e3ce-11e9-9305-6ebc1ac70186.png)

I found that If I go into my ./tmux.config file and put in the line
`set -g @nord_tmux_no_patched_font "1"`
The bars and symbols disappear competently.

![Screenshot from 2019-09-30 22-08-04](https://user-images.githubusercontent.com/51177491/65935687-d2bed280-e3ce-11e9-8225-5fb97501e706.png)

I also know that my terminal supports and is running 24 bit True Color.

On top of that, all of the text within the terminal is white. So, they folders don't inherent their color from the Nordic theme that is already in my Gnome Terminal

**Comment by Kaddu720** [comment]
I resolved the issue of all of my folders being white by adding the line

`set-option -g default-command bash`

in `tmux.conf`

**Comment by arcticicestudio** [comment]
Hi @Kaddu720 :wave:, thanks for your contribution :+1:
The problem of the glyphs is not the terminal color space, but the **font type/family** you're using. You must use a _patched_ font which is a font type especially modified to work with terminals. There are projects like [nerd-fonts][] that provide _patched_ fonts for popular font families.

The purpose of the `@nord_tmux_no_patched_font` option is to remove the special characters at all, so they are not invisible but not rendered at all. The result of the arrow being not shown is by design.

Regarding the white folders: This is also not part of this theme but for the database used by the [`ls` command][ls] to control colors. On Linux system this is the [`dircolors` command][dc] also used by _Bash_ by default. To use Nord as colors for the `ls` command install the [_nord-dircolors_ port project][p].

Please let me know if applying these solutions helped to solve your problem :smile: 

[nerd-fonts]: https://github.com/ryanoasis/nerd-fonts
[ls]: https://en.wikipedia.org/wiki/Ls#Behavior
[dc]: https://linux.die.net/man/5/dir_colors
[p]: https://www.nordtheme.com/ports/dircolors

**Comment by Kaddu720** [comment]
You're institutions worked perfectly. 

Thank you so much!
