### ISSUE TITLE
troubles in Ubuntu

### ISSUE THREAD

**Issue by Slavjan** [arcticicestudio/nord-tmux#49]
I have trouble with turning on themes in ubuntu-terminal.

background-color still default
and bottom bar have some strange symbols.

Please advice what I do not right?
![Screenshot from 2020-07-17 04-02-19](https://user-images.githubusercontent.com/10784962/87722844-04304f80-c7e3-11ea-8282-7bc6c661425c.png)
![Screenshot from 2020-07-17 04-17-39](https://user-images.githubusercontent.com/10784962/87723796-85d4ad00-c7e4-11ea-9bba-edf446d7e3a4.png)

**Comment by waitqaq** [comment]
i also get this problem,are you solve it?

**Comment by arcticicestudio** [comment]
Hi @Slavjan and @alone-zd, please make sure to follow the [installation instructions from the official documentation][d], especially the info box at the top that states that Nord for tmux **must be used with a Nord terminal emulator theme** in order to work properly.
Looking at the screenshots I can see that the colors are the most likely the ones from the default color palette which means Nord's color values (RGB in hexadecimal format) are currently not available within the terminal or it has not been set as the active color scheme. You must install [Nord for GNOME Terminal][ngt] since Ubuntu comes with the [GNOME terminal][gt] installed by default. 

[d]: https://www.nordtheme.com/docs/ports/tmux/installation
[ngt]: https://github.com/arcticicestudio/nord-gnome-terminal
[gt]: https://help.gnome.org/users/gnome-terminal/stable

**Comment by waitqaq** [comment]
is not the color's problem,you can see the bottom of tmux is has some problems,i make sure have the GNOME termainal,but it can't solve it

**Comment by euglevi** [comment]
I have more or less the same issue as @Slavjan and @alone-zd. I use Gnome Terminal with a Nord theme. In my case, the background color is fine, but I get exactly the same weird bottom bar. Any ideas?

**Comment by arcticicestudio** [comment]
Have you made sure to also switch to the [newly created “Nord“ GNOME terminal profile][ph] after running the installation script? Otherwise the palette is not active or must be set for already existing profile(s) manually.

@Slavjan @alone-zd @euglevi Can you please share some details about your setup like…

1. …your Ubuntu and GNOME terminal version.
2. …your _tmux_ version.
3. …the Nord tmux version you're running.

Also maybe try to checkout PR #34 to see if the changes that have been made there also fix your problem.
If this is not the case I'd need to create a virtual machine that runs your Ubuntu version(s) to see if the Ubuntu team messed something up again. 

[ph]: https://github.com/arcticicestudio/nord-gnome-terminal#profile-handling

**Comment by waitqaq** [comment]
![image](https://user-images.githubusercontent.com/57276845/89603689-3beb5e00-d89c-11ea-8222-8dbf69367855.png)
 you con see that i had in nord,but the tmux's style has some troubles.
Ubuntu:18.04.3 LTS
terminal:GNOME Shell 3.28.4

**Comment by waitqaq** [comment]
![image](https://user-images.githubusercontent.com/57276845/89604203-5b36bb00-d89d-11ea-8579-bd26359c1b40.png)

**Comment by arcticicestudio** [comment]
@alone-zd Ah I see, the colors seem to be working fine, but the weird symbols in the tmux bar are caused by encoding problems. As you can see [in the source code][s] this theme uses (special) characters like ► which are quite often not supported by terminal fonts. Especially in your case there might also be some problems due to additional support for [CJK][w].
In order to fix this you need to install and use a “patched“ font family for the terminal that supports such characters. Check out projects like [Nerd Fonts][nf] that provides patched fonts for terminal usage.

[s]: https://github.com/arcticicestudio/nord-tmux/blob/412e300/src/nord-status-content.conf#L20-L22
[w]: https://en.wikipedia.org/wiki/Chinese_character_encoding
[nf]: https://github.com/ryanoasis/nerd-fonts

**Comment by waitqaq** [comment]
which font i should get?it looks  so large

**Comment by waitqaq** [comment]
ok,i solve it ,it just because a font.when i got this font ,i prefectly solve it                  (PowerlineSymbols.otf)in https://github.com/powerline/powerline.  i wish that it can help you

**Comment by arcticicestudio** [comment]
@waitself Nice to hear that it works for your now 👍🏼 
Font problems are often not directly related to this theme but the set up of the user. It is also described in the [Nord tmux “Font Rendering“ customization documentation][1].

[1]: https://www.nordtheme.com/docs/ports/tmux/configuration#font-rendering
